#!/usr/bin/env python
"""
Example of how to create git-like execution manager with monolith.
This is completely fake command.
"""
from monolith.cli import ExecutionManager
from monolith.cli import LabelCommand
from monolith.cli import SingleLabelCommand
from monolith.cli import arg


class AddCommand(LabelCommand):
    name = 'add'
    
    def handle_label(self, label, namespace):
        print "A %s" % label


class InitCommand(SingleLabelCommand):
    name = 'init'
    label = 'directory'
    label_required = False
    label_default_value = '.'
    args = SingleLabelCommand.args + [
        arg('--bare', help='Create a bare repository.', default=False, action='store_true'),
    ]

    def handle_label(self, label, namespace):
        print "Initialized empty Git repository in %s.git" % label


def main():
    manager = ExecutionManager()
    manager.register('add', AddCommand)
    manager.register('init', InitCommand)
    manager.execute()


if __name__ == '__main__':
    main()

