#!/usr/bin/env python
"""
Example of how to create git-like execution manager with monolith.
This is completely fake command.
"""
from monolith.cli import ExecutionManager
from monolith.cli import LabelCommand
from monolith.cli import SingleLabelCommand


class AddCommand(LabelCommand):
    name = 'add'
    
    def handle_label(self, label, namespace):
        print "A %s" % label


class InitCommand(SingleLabelCommand):
    name = 'init'

    def handle_label(self, label, namespace):
        print "Initializing git repository at %s.git" % label


def main():
    manager = ExecutionManager()
    manager.register(AddCommand)
    manager.register(InitCommand)
    manager.execute()


if __name__ == '__main__':
    main()

